import React, { useState, useRef } from 'react';
import { publicMenuAPI } from '../api/client';
import styles from '../styles/MenuPdfExport.module.scss';

/**
 * MenuPdfExport - Generates a PDF from a menu
 * Uses html2pdf.js for client-side PDF generation
 */
function MenuPdfExport({ menu, onClose, onError }) {
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [menuData, setMenuData] = useState(null);
  const contentRef = useRef(null);

  // Fetch menu data when component mounts
  React.useEffect(() => {
    fetchMenuData();
  }, [menu.share_token]);

  const fetchMenuData = async () => {
    try {
      setLoading(true);
      // Extract share token from URL or use directly
      const token = menu.share_token || menu.share_url?.split('/').pop();
      const response = await publicMenuAPI.get(token);
      setMenuData(response.data);
    } catch (err) {
      console.error('Error fetching menu data:', err);
      onError?.('Failed to load menu data');
      onClose?.();
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    if (!contentRef.current) return;

    setGenerating(true);
    try {
      // Dynamically import html2pdf.js
      const html2pdf = (await import('html2pdf.js')).default;

      const element = contentRef.current;
      const menuTitle = menuData?.menu?.title || 'Menu';

      const opt = {
        margin: [0.5, 0.5, 0.5, 0.5],
        filename: `${menuTitle.replace(/[^a-z0-9]/gi, '_')}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          letterRendering: true,
        },
        jsPDF: {
          unit: 'in',
          format: 'letter',
          orientation: 'portrait'
        },
        pagebreak: { mode: 'avoid-all' }
      };

      await html2pdf().set(opt).from(element).save();
      onClose?.();
    } catch (err) {
      console.error('Error generating PDF:', err);
      onError?.('Failed to generate PDF. Make sure html2pdf.js is installed.');
    } finally {
      setGenerating(false);
    }
  };

  const theme = menu.theme || 'rustic';
  const colorMode = menu.color_mode || 'dark';

  if (loading) {
    return (
      <div className={styles.overlay}>
        <div className={styles.modal}>
          <div className={styles.loading}>
            <div className={styles.spinner}></div>
            <p>Loading menu data...</p>
          </div>
        </div>
      </div>
    );
  }

  const items = menuData?.items || [];

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.modal} onClick={e => e.stopPropagation()}>
        <div className={styles.header}>
          <h2>Export Menu to PDF</h2>
          <button className={styles.closeButton} onClick={onClose}>×</button>
        </div>

        <div className={styles.preview}>
          {/* PDF Content - this is what gets exported */}
          <div
            ref={contentRef}
            className={`${styles.pdfContent} theme-${theme} mode-${colorMode}`}
          >
            <div className={styles.pdfHeader}>
              <div className={styles.pdfBrand}>BarrelChatter</div>
              <h1 className={styles.pdfTitle}>{menuData?.menu?.title}</h1>
              <p className={styles.pdfSubtitle}>
                {items.length} {items.length === 1 ? 'bottle' : 'bottles'} in stock
              </p>
            </div>

            <div className={styles.pdfList}>
              {items.map(item => (
                <div key={item.id} className={styles.pdfItem}>
                  <div className={styles.pdfItemInfo}>
                    <span className={styles.pdfItemName}>{item.bottle.name}</span>
                    {item.bottle.distillery && (
                      <span className={styles.pdfItemDistillery}>{item.bottle.distillery}</span>
                    )}
                  </div>
                  <div className={styles.pdfItemDetails}>
                    {item.bottle.age_statement && (
                      <span className={styles.pdfItemAge}>{item.bottle.age_statement}</span>
                    )}
                    {item.bottle.proof && (
                      <span className={styles.pdfItemProof}>{item.bottle.proof}°</span>
                    )}
                    {item.bottle.type && (
                      <span className={styles.pdfItemType}>{item.bottle.type}</span>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div className={styles.pdfFooter}>
              <p>Generated by BarrelChatter</p>
            </div>
          </div>
        </div>

        <div className={styles.actions}>
          <button
            className={styles.cancelButton}
            onClick={onClose}
            disabled={generating}
          >
            Cancel
          </button>
          <button
            className={styles.downloadButton}
            onClick={handleDownload}
            disabled={generating || items.length === 0}
          >
            {generating ? 'Generating...' : 'Download PDF'}
          </button>
        </div>
      </div>
    </div>
  );
}

export default MenuPdfExport;
